[project]
name = "k8s-health-agent"
version = "0.2.3"
description = "Agent for monitoring and managing Kubernetes clusters"
requires-python = ">=3.14"
dependencies = [
    "orrery-core",
    "kubernetes>=36.0.2",
]

[tool.uv.sources]
orrery-core = { workspace = true }

[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["k8s_health_agent*"]
